packages:
  - "."
  - "apps/*"
  - "packages/*"

allowBuilds:
  unrs-resolver: true

onlyBuiltDependencies:
  - unrs-resolver

overrides:
  "brace-expansion@>=4.0.0 <5.0.12": "5.0.12"
  "decode-uri-component@<=0.4.2": "0.5.0"
  "js-yaml@>=4.0.0 <4.3.2": "4.3.2"
  "uuid@<11.1.1": "11.1.1"
