import Link from "next/link";
import { ChevronLeft, ChevronRight, ExternalLink } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { requireBusinessContext } from "@/lib/business-context";
import { dateKey, formatDate, formatTime } from "@/lib/format";

type CalendarAppointment = { id: string; employee_id: string; starts_at: string; ends_at: string; status: "pending" | "confirmed" | "completed" | "cancelled" | "no_show"; customers: { full_name: string } | { full_name: string }[] | null; appointment_items: { name_snapshot: string }[] | null };
type Search = Promise<{ date?: string; view?: string }>;
function one<T>(value: T | T[] | null) { return Array.isArray(value) ? value[0] : value; }
function validDate(value: string | undefined) { return value && /^\d{4}-\d{2}-\d{2}$/.test(value) && !Number.isNaN(new Date(`${value}T12:00:00Z`).getTime()) ? value : dateKey(new Date()); }
function shift(value: string, days: number) { const date = new Date(`${value}T12:00:00Z`); date.setUTCDate(date.getUTCDate() + days); return date.toISOString().slice(0, 10); }

export default async function BusinessCalendarPage({ searchParams }: { searchParams: Search }) {
  const { supabase, business } = await requireBusinessContext(["OWNER", "MANAGER", "EMPLOYEE"]);
  const params = await searchParams; const selected = validDate(params.date); const view = params.view === "week" || params.view === "month" ? params.view : "day";
  const selectedDate = new Date(`${selected}T12:00:00Z`); const weekday = (selectedDate.getUTCDay() + 6) % 7;
  let fromDate = selected; let toDate = shift(selected, 1); let step = 1;
  if (view === "week") { fromDate = shift(selected, -weekday); toDate = shift(fromDate, 7); step = 7; }
  if (view === "month") { fromDate = `${selected.slice(0, 7)}-01`; const next = new Date(`${fromDate}T12:00:00Z`); next.setUTCMonth(next.getUTCMonth() + 1); toDate = next.toISOString().slice(0, 10); step = 30; }
  const [{ data: employeeRows }, { data: appointmentRows }, { data: hourRows }] = await Promise.all([
    supabase.from("employees").select("id,display_name").eq("business_id", business.id).eq("active", true).order("sort_order").order("created_at"),
    supabase.from("appointments").select("id,employee_id,starts_at,ends_at,status,customers(full_name),appointment_items(name_snapshot)").eq("business_id", business.id).gte("starts_at", `${fromDate}T00:00:00+03:00`).lt("starts_at", `${toDate}T00:00:00+03:00`).order("starts_at"),
    supabase.from("employee_working_hours").select("employee_id,starts_at,ends_at,weekday").eq("business_id", business.id),
  ]);
  const appointments = (appointmentRows ?? []) as unknown as CalendarAppointment[]; const employees = employeeRows ?? [];
  const previous = shift(selected, -step); const next = shift(selected, step);
  const viewQuery = (date: string, nextView = view) => `/business/calendar?date=${date}&view=${nextView}`;
  return <div className="mx-auto max-w-[1400px]"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-bold">Randevu Takvimi</h1><p className="mt-1 text-sm text-[#777781]">Ekibin gerçek programı ve randevu durumu.</p></div><Link href={`/business/${business.slug}`} target="_blank" className="inline-flex h-10 items-center gap-2 rounded-xl bg-[#6C4BF4] px-4 text-xs font-semibold text-white">Müşteri sayfası <ExternalLink className="h-4 w-4" /></Link></div><div className="surface mt-6 overflow-hidden"><div className="flex flex-wrap items-center gap-3 border-b border-[#ECECF1] p-4"><Link href={viewQuery(dateKey(new Date()))} className="rounded-lg border border-[#E8E8EE] px-3 py-2 text-xs font-medium">Bugün</Link><div className="flex"><Link href={viewQuery(previous)} className="grid h-8 w-8 place-items-center rounded-l-lg border border-[#E8E8EE]"><ChevronLeft className="h-4 w-4" /></Link><Link href={viewQuery(next)} className="grid h-8 w-8 place-items-center rounded-r-lg border-y border-r border-[#E8E8EE]"><ChevronRight className="h-4 w-4" /></Link></div><strong className="text-sm">{view === "month" ? new Intl.DateTimeFormat("tr-TR", { month: "long", year: "numeric" }).format(selectedDate) : view === "week" ? `${formatDate(`${fromDate}T12:00:00Z`)} – ${formatDate(`${shift(toDate, -1)}T12:00:00Z`)}` : formatDate(`${selected}T12:00:00Z`, { weekday: "long", day: "numeric", month: "long", year: "numeric" })}</strong><div className="ml-auto flex rounded-lg bg-[#F1F1F4] p-1">{[["day", "Gün"], ["week", "Hafta"], ["month", "Ay"]].map(([key, label]) => <Link key={key} href={viewQuery(selected, key)} className={`rounded-md px-3 py-1.5 text-xs font-medium ${view === key ? "bg-white text-[#6C4BF4] shadow-sm" : ""}`}>{label}</Link>)}</div></div>{view === "day" ? <DayView selected={selected} employees={employees} appointments={appointments} hours={hourRows ?? []} /> : <ListView appointments={appointments} />}</div></div>;
}

function DayView({ selected, employees, appointments, hours }: { selected: string; employees: { id: string; display_name: string }[]; appointments: CalendarAppointment[]; hours: { employee_id: string; starts_at: string; ends_at: string; weekday: number }[] }) {
  if (!employees.length) return <Empty title="Takvim için çalışan ekle" body="Aktif çalışanlar oluşturulduğunda sütunları burada görünür." />;
  const startHour = 8; const endHour = 22; const slotHeight = 64; const selectedDate = new Date(`${selected}T12:00:00Z`); const weekday = (selectedDate.getUTCDay() + 6) % 7;
  return <div className="overflow-x-auto"><div style={{ minWidth: `${Math.max(760, employees.length * 220 + 70)}px` }}><div className="grid border-b border-[#ECECF1]" style={{ gridTemplateColumns: `70px repeat(${employees.length}, minmax(190px, 1fr))` }}><div />{employees.map((employee) => { const periods = hours.filter((row) => row.employee_id === employee.id && row.weekday === weekday); return <div key={employee.id} className="border-l border-[#ECECF1] p-4 text-center"><strong className="text-xs">{employee.display_name}</strong><span className="mt-1 block text-[10px] text-[#22A95A]">{periods.length ? periods.map((p) => `${p.starts_at.slice(0, 5)}–${p.ends_at.slice(0, 5)}`).join(", ") : "İşletme saatleri"}</span></div>; })}</div><div className="relative" style={{ height: (endHour - startHour) * slotHeight }}><div className="absolute inset-0 grid" style={{ gridTemplateColumns: `70px repeat(${employees.length}, minmax(190px, 1fr))` }}>{Array.from({ length: employees.length + 1 }).map((_, index) => <div key={index} className={index ? "border-l border-[#ECECF1]" : ""} />)}</div>{Array.from({ length: endHour - startHour }).map((_, index) => <div key={index} className="absolute inset-x-0 flex border-t border-[#ECECF1]" style={{ top: index * slotHeight, height: slotHeight }}><span className="w-[70px] -translate-y-2 bg-white pr-3 text-right text-[10px] text-[#91919A]">{String(startHour + index).padStart(2, "0")}:00</span></div>)}{appointments.filter((appointment) => appointment.status !== "cancelled").map((appointment) => { const column = employees.findIndex((employee) => employee.id === appointment.employee_id); if (column < 0) return null; const local = new Date(appointment.starts_at); const hour = Number(new Intl.DateTimeFormat("en-GB", { hour: "2-digit", hour12: false, timeZone: "Europe/Istanbul" }).format(local)); const minute = Number(new Intl.DateTimeFormat("en-GB", { minute: "2-digit", timeZone: "Europe/Istanbul" }).format(local)); const duration = Math.max(30, (new Date(appointment.ends_at).getTime() - local.getTime()) / 60000); const top = ((hour - startHour) * 60 + minute) / 60 * slotHeight; const left = `calc(70px + ${column} * ((100% - 70px) / ${employees.length}) + 5px)`; const width = `calc((100% - 70px) / ${employees.length} - 10px)`; return <Link href="/business/appointments" key={appointment.id} className="absolute z-10 overflow-hidden rounded-lg border-l-[3px] border-[#6C4BF4] bg-[#EEE9FF] p-2 text-left shadow-sm transition hover:z-20 hover:brightness-[.98]" style={{ left, width, top: Math.max(0, top), height: Math.max(38, duration / 60 * slotHeight - 3) }}><strong className="block truncate text-[11px]">{one(appointment.customers)?.full_name ?? "Müşteri"}</strong><span className="mt-1 block truncate text-[10px] text-[#666672]">{formatTime(appointment.starts_at)} · {appointment.appointment_items?.[0]?.name_snapshot ?? "Hizmet"}</span></Link>; })}</div></div></div>;
}

function ListView({ appointments }: { appointments: CalendarAppointment[] }) { const groups = Map.groupBy(appointments, (item) => dateKey(item.starts_at)); if (!appointments.length) return <Empty title="Bu dönemde randevu yok" body="Yeni rezervasyonlar geldiğinde takvime otomatik işlenir." />; return <div className="grid gap-5 p-5">{Array.from(groups.entries()).map(([date, rows]) => <section key={date}><h2 className="mb-2 text-sm font-semibold">{formatDate(`${date}T12:00:00Z`, { weekday: "long", day: "numeric", month: "long" })}</h2><div className="grid gap-2">{rows.map((row) => <Link href="/business/appointments" key={row.id} className="flex flex-wrap items-center gap-3 rounded-xl border border-[#ECECF1] p-3 hover:bg-[#FAF9FF]"><strong className="w-12 text-xs">{formatTime(row.starts_at)}</strong><span className="min-w-[180px] flex-1 text-xs">{one(row.customers)?.full_name ?? "Müşteri"} · {row.appointment_items?.[0]?.name_snapshot ?? "Hizmet"}</span><Badge tone={row.status === "confirmed" ? "green" : row.status === "pending" ? "amber" : row.status === "cancelled" ? "red" : "gray"}>{row.status}</Badge></Link>)}</div></section>)}</div>; }
function Empty({ title, body }: { title: string; body: string }) { return <div className="grid min-h-64 place-items-center p-8 text-center"><div><h2 className="font-semibold">{title}</h2><p className="mt-2 text-sm text-[#777781]">{body}</p></div></div>; }
