"use client";
import { Star } from "lucide-react";
import { useState, useTransition } from "react";
import { replyToReview } from "@/app/business/actions";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { formatDate } from "@/lib/format";
export type BusinessReview = { id: string; rating: number; comment: string; reply: string; status: string; createdAt: string };
export function BusinessReviewsPanel({ initialReviews }: { initialReviews: BusinessReview[] }) { const [reviews, setReviews] = useState(initialReviews); const [pending, startTransition] = useTransition(); const [message, setMessage] = useState(""); function reply(id: string, form: FormData) { const text = String(form.get("reply") ?? ""); startTransition(async () => { const result = await replyToReview(id, text); setMessage(result.message); if (result.ok) setReviews((items) => items.map((item) => item.id === id ? { ...item, reply: text } : item)); }); } return <section className="surface mt-4 p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Doğrulanmış müşteri değerlendirmeleri</h2><p className="mt-1 text-xs text-[#777781]">Yalnız tamamlanmış randevulardan gelir; yayın öncesi moderasyondan geçer.</p></div><Badge tone="purple">{reviews.length} yorum</Badge></div>{message && <p className="mt-4 text-xs text-[#5B3BE7]">{message}</p>}<div className="mt-5 grid gap-4 md:grid-cols-2">{reviews.map((review) => <article key={review.id} className="rounded-2xl border border-[#ECECF1] p-4"><div className="flex items-center gap-2"><span className="flex">{Array.from({ length: 5 }).map((_, index) => <Star key={index} className={`h-4 w-4 ${index < review.rating ? "fill-[#F5B942] text-[#F5B942]" : "text-[#D5D5DC]"}`} />)}</span><Badge tone={review.status === "approved" ? "green" : review.status === "rejected" ? "red" : "gray"}>{review.status === "approved" ? "Yayında" : review.status === "pending" ? "İncelemede" : review.status}</Badge><span className="ml-auto text-[10px] text-[#888894]">{formatDate(review.createdAt)}</span></div><p className="mt-3 text-sm text-[#4F4F58]">{review.comment || "Yorum metni bırakılmadı."}</p>{review.reply ? <div className="mt-3 rounded-xl bg-[#F8F7FC] p-3 text-xs"><strong>Yanıtınız</strong><p className="mt-1 text-[#666672]">{review.reply}</p></div> : <form action={reply.bind(null, review.id)} className="mt-3 flex gap-2"><input name="reply" minLength={2} maxLength={2000} required placeholder="İşletme yanıtı..." className="h-10 flex-1 rounded-xl border px-3 text-xs outline-none focus:border-[#6C4BF4]" /><Button disabled={pending} className="h-10">Yanıtla</Button></form>}</article>)}{!reviews.length && <p className="text-sm text-[#777781]">Henüz değerlendirme yok.</p>}</div></section>; }
