import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, BadgeCheck, Clock3, Globe, MapPin, Navigation, Phone, Plus, Star } from "lucide-react";
import { notFound } from "next/navigation";
import { BusinessDetailActions } from "@/components/business-detail-actions";
import { BusinessDetailMap } from "@/components/business-detail-map";
import { BusinessGalleryLauncher } from "@/components/business-gallery";
import { MobileNav } from "@/components/mobile-nav";
import { SiteHeader } from "@/components/site-header";
import { Badge } from "@/components/ui/badge";
import { ButtonLink } from "@/components/ui/button";
import { BRAND } from "@/config/brand";
import { getMarketplaceBusiness } from "@/lib/marketplace";
import { canonicalBusinessPath } from "@/lib/seo";

type Props = { params: Promise<{ slug: string }> };
const dayNames = ["Pazartesi", "Salı", "Çarşamba", "Perşembe", "Cuma", "Cumartesi", "Pazar"];
const schemaDays = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];
function price(value: number) { return new Intl.NumberFormat("tr-TR", { style: "currency", currency: "TRY", maximumFractionDigits: 0 }).format(value); }
function shortTime(value: string | null | undefined) { return value?.slice(0, 5) ?? ""; }

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const business = await getMarketplaceBusiness((await params).slug); if (!business) return { title: "İşletme bulunamadı", robots: { index: false, follow: false } };
  const canonical = canonicalBusinessPath(business); const description = `${business.district}, ${business.city} bölgesindeki ${business.name}: hizmetler, fiyatlar, doğrulanmış müşteri yorumları ve online randevu.`;
  return { title: `${business.name} | ${business.category} randevusu`, description, alternates: { canonical }, openGraph: { type: "website", locale: "tr_TR", url: canonical, siteName: BRAND.name, title: `${business.name} — online randevu`, description, images: [{ url: business.image, alt: `${business.name} işletme görseli` }] }, twitter: { card: "summary_large_image", title: business.name, description, images: [business.image] } };
}

export default async function BusinessDetailPage({ params }: Props) {
  const business = await getMarketplaceBusiness((await params).slug); if (!business) notFound(); const canonicalPath = canonicalBusinessPath(business); const siteUrl = (process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000").replace(/\/$/, "");
  const localBusiness: Record<string, unknown> = { "@context": "https://schema.org", "@type": business.category === "Veteriner" ? "VeterinaryCare" : business.category === "Fitness" || business.category === "Pilates" ? "SportsActivityLocation" : "HealthAndBeautyBusiness", "@id": `${siteUrl}${canonicalPath}#business`, url: `${siteUrl}${canonicalPath}`, name: business.name, description: business.description || `${business.category} hizmetleri`, image: business.gallery, telephone: business.phone || undefined, priceRange: business.startingPrice ? `${price(business.startingPrice)}+` : undefined, address: { "@type": "PostalAddress", streetAddress: business.address, addressLocality: business.district, addressRegion: business.city, addressCountry: "TR" }, geo: { "@type": "GeoCoordinates", latitude: business.lat, longitude: business.lng }, openingHoursSpecification: (business.hours ?? []).filter((hour) => !hour.closed && hour.opensAt && hour.closesAt).map((hour) => ({ "@type": "OpeningHoursSpecification", dayOfWeek: `https://schema.org/${schemaDays[hour.weekday]}`, opens: shortTime(hour.opensAt), closes: shortTime(hour.closesAt) })), hasOfferCatalog: { "@type": "OfferCatalog", name: `${business.name} hizmetleri`, itemListElement: business.services.map((service) => ({ "@type": "Offer", priceCurrency: "TRY", price: service.price, itemOffered: { "@type": "Service", name: service.name, description: service.description || undefined } })) } };
  if (business.reviews > 0 && business.rating > 0) localBusiness.aggregateRating = { "@type": "AggregateRating", ratingValue: business.rating, reviewCount: business.reviews, bestRating: 5, worstRating: 1 };
  if (business.reviewItems?.length) localBusiness.review = business.reviewItems.slice(0, 10).map((review) => ({ "@type": "Review", author: { "@type": "Person", name: "Doğrulanmış müşteri" }, datePublished: review.createdAt.slice(0, 10), reviewRating: { "@type": "Rating", ratingValue: review.rating, bestRating: 5, worstRating: 1 }, reviewBody: review.comment || undefined }));
  const breadcrumb = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Ana sayfa", item: siteUrl }, { "@type": "ListItem", position: 2, name: "Keşfet", item: `${siteUrl}/kesfet` }, { "@type": "ListItem", position: 3, name: business.category, item: `${siteUrl}/kesfet?category=${encodeURIComponent(business.category)}` }, { "@type": "ListItem", position: 4, name: business.name, item: `${siteUrl}${canonicalPath}` }] };
  const statusText = business.todayHours?.closed || !business.todayHours ? "Bugün kapalı" : business.open ? `Açık · ${shortTime(business.todayHours.closesAt)}'da kapanır` : `Kapalı · ${shortTime(business.todayHours.opensAt)}'da açılır`;

  return <><SiteHeader search /><main className="pb-28 md:pb-16"><div className="container-shell py-4"><div className="flex items-center gap-2 text-xs text-[#777781]"><Link href="/kesfet" className="flex items-center gap-1"><ArrowLeft className="h-3.5 w-3.5" /> Keşfet</Link><span>/</span><span>{business.category}</span><span>/</span><strong className="truncate text-[#27272A]">{business.name}</strong></div></div>
    <section className="container-shell grid gap-4 md:grid-cols-[2fr_1fr]"><div className="relative min-h-[270px] overflow-hidden rounded-[24px] max-md:-mx-4 max-md:rounded-none md:min-h-[440px]"><BusinessGalleryLauncher images={business.gallery} businessName={business.name} priority showCount={false} className="absolute inset-0 h-full w-full" sizes="(max-width: 768px) 100vw, 760px" /><div className="absolute right-4 top-4 z-10"><BusinessDetailActions businessId={business.id} slug={business.slug} name={business.name} /></div><Badge className="pointer-events-none absolute bottom-4 left-4 z-10 bg-[#15151A]/80 text-white"><Star className="mr-1 h-3.5 w-3.5 fill-[#F5B942] text-[#F5B942]" /> {business.reviews ? `${business.rating.toFixed(1)} (${business.reviews})` : "Yeni işletme"}</Badge><span className="pointer-events-none absolute bottom-4 right-4 z-10 rounded-lg bg-black/70 px-3 py-2 text-[10px] font-semibold text-white">{business.gallery.length} fotoğraf</span></div><div className="hidden grid-rows-2 gap-4 md:grid">{business.gallery.slice(1, 3).map((image, index) => <BusinessGalleryLauncher key={`${image}-${index}`} images={business.gallery} businessName={business.name} initialIndex={index + 1} showCount={index === Math.min(1, business.gallery.slice(1, 3).length - 1)} className="h-full w-full rounded-[20px]" sizes="380px" />)}</div></section>
    <section className="container-shell mt-7 grid gap-8 lg:grid-cols-[minmax(0,1fr)_340px]"><div className="min-w-0"><div><div className="flex items-center gap-2"><h1 className="text-3xl font-bold tracking-[-.035em] md:text-4xl">{business.name}</h1>{business.verified && <BadgeCheck className="h-6 w-6 fill-[#6C4BF4] text-white" />}</div><p className="mt-1.5 text-sm text-[#777781]">{business.category}</p><p className="mt-3 flex items-start gap-2 text-sm leading-5 text-[#555560]"><MapPin className="mt-0.5 h-4 w-4 shrink-0 text-[#6C4BF4]" /> {business.address}, {business.district}/{business.city}</p><p className={`mt-2 flex items-center gap-2 text-sm font-semibold ${business.open ? "text-[#15803D]" : "text-[#777781]"}`}><Clock3 className="h-4 w-4" />{statusText}</p></div>
      <div className="mt-5 flex flex-wrap gap-3 border-y border-[#ECECF1] py-4"><a href={`https://www.openstreetmap.org/directions?to=${business.lat},${business.lng}`} target="_blank" rel="noreferrer" className="inline-flex h-10 items-center gap-2 rounded-xl border border-[#E8E8EE] px-4 text-xs font-medium hover:bg-[#F7F5FF]"><Navigation className="h-4 w-4" /> Yol Tarifi</a>{business.phone && <a href={`tel:${business.phone}`} className="inline-flex h-10 items-center gap-2 rounded-xl border border-[#E8E8EE] px-4 text-xs font-medium hover:bg-[#F7F5FF]"><Phone className="h-4 w-4" /> Ara</a>}{business.website && <a href={business.website} target="_blank" rel="noreferrer" className="inline-flex h-10 items-center gap-2 rounded-xl border border-[#E8E8EE] px-4 text-xs font-medium hover:bg-[#F7F5FF]"><Globe className="h-4 w-4" /> Web Sitesi</a>}</div>
      <nav className="mt-7 flex gap-7 overflow-x-auto border-b border-[#E8E8EE] text-sm font-medium hide-scrollbar"><a href="#services" className="border-b-2 border-[#6C4BF4] px-1 pb-4 text-[#6C4BF4]">Hizmetler</a><a href="#reviews" className="shrink-0 pb-4">Yorumlar ({business.reviews})</a><a href="#employees" className="shrink-0 pb-4">Çalışanlar</a><a href="#about" className="shrink-0 pb-4">Hakkında</a></nav>
      <section id="services" className="scroll-mt-24 py-7"><h2 className="text-xl font-bold">Hizmetler</h2>{business.services.length ? <div className="mt-4 divide-y divide-[#ECECF1] rounded-2xl border border-[#E8E8EE] bg-white">{business.services.map((service) => <div key={service.id} className="flex items-center gap-4 p-5"><div className="min-w-0 flex-1"><h3 className="font-semibold">{service.name}</h3>{service.description && <p className="mt-1 text-xs text-[#777781]">{service.description}</p>}<span className="mt-2 block text-xs text-[#777781]">{service.duration} dk</span></div><strong className="shrink-0 text-sm">{price(service.price)}</strong><ButtonLink aria-label={`${service.name} seç`} href={`/booking/${business.slug}?service=${service.id}`} className="h-9 px-4 max-sm:grid max-sm:w-9 max-sm:place-items-center max-sm:rounded-full max-sm:p-0"><span className="max-sm:hidden">Seç</span><Plus className="hidden h-4 w-4 max-sm:block" /></ButtonLink></div>)}</div> : <Empty text="Bu işletme henüz hizmet yayınlamadı." />}</section>
      <section id="employees" className="scroll-mt-24 border-t border-[#E8E8EE] py-7"><h2 className="text-xl font-bold">Uzmanlar</h2>{business.employees.length ? <div className="mt-5 grid gap-4 sm:grid-cols-2">{business.employees.map((employee) => <div key={employee.id} className="surface flex items-center gap-4 p-4"><div className="relative h-16 w-16 overflow-hidden rounded-full bg-[#F0ECFF]"><Image src={employee.avatar} alt={`${employee.name} profil fotoğrafı`} fill className="object-cover" sizes="64px" /></div><div><strong>{employee.name}</strong><p className="mt-1 text-xs text-[#777781]">{employee.role}</p><span className="mt-2 block text-xs text-[#777781]">{employee.services.length} hizmet</span></div></div>)}</div> : <Empty text="Ekip bilgileri yakında eklenecek." />}</section>
      <section id="reviews" className="scroll-mt-24 border-t border-[#E8E8EE] py-7"><div className="flex items-end gap-4"><strong className="text-5xl">{business.reviews ? business.rating.toFixed(1) : "—"}</strong><div><div className="flex gap-1">{Array.from({ length: 5 }).map((_, index) => <Star key={index} className={`h-4 w-4 ${business.reviews && index < Math.round(business.rating) ? "fill-[#F5B942] text-[#F5B942]" : "text-[#D6D6DC]"}`} />)}</div><p className="mt-1 text-xs text-[#777781]">{business.reviews} doğrulanmış yorum</p></div></div>{business.reviewItems?.length ? <div className="mt-6 grid gap-4 md:grid-cols-2">{business.reviewItems.map((review) => <article key={review.id} className="surface p-5"><div className="flex items-center justify-between"><strong className="text-sm">Doğrulanmış müşteri</strong><Badge tone="green">Tamamlanmış randevu</Badge></div><div className="mt-3 flex gap-1">{Array.from({ length: 5 }).map((_, index) => <Star key={index} className={`h-3.5 w-3.5 ${index < review.rating ? "fill-[#F5B942] text-[#F5B942]" : "text-[#D6D6DC]"}`} />)}</div><p className="mt-3 text-sm leading-6 text-[#555560]">{review.comment || "Puan verildi; yazılı yorum bırakılmadı."}</p><span className="mt-3 block text-xs text-[#91919A]">{new Intl.DateTimeFormat("tr-TR", { day: "numeric", month: "long", year: "numeric" }).format(new Date(review.createdAt))}</span>{review.businessReply && <div className="mt-4 rounded-xl bg-[#F8F7FC] p-3 text-xs"><strong>İşletmenin yanıtı</strong><p className="mt-1 leading-5 text-[#666672]">{review.businessReply}</p></div>}</article>)}</div> : <Empty text="Henüz doğrulanmış değerlendirme yok. Yorumlar yalnız tamamlanan randevulardan alınır." />}</section>
      <section id="about" className="scroll-mt-24 border-t border-[#E8E8EE] py-7"><h2 className="text-xl font-bold">Hakkında</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-[#666672]">{business.description || `${business.name}, ${business.district} bölgesinde ${business.category.toLocaleLowerCase("tr-TR")} hizmetleri sunar.`}</p><div className="mt-6 grid gap-5 md:grid-cols-[1fr_.8fr]"><div className="h-64 overflow-hidden rounded-2xl"><BusinessDetailMap business={business} /></div><div className="surface p-5"><h3 className="font-semibold">Çalışma saatleri</h3><div className="mt-4 grid gap-2">{dayNames.map((name, weekday) => { const hour = business.hours?.find((item) => item.weekday === weekday); return <div key={name} className="flex justify-between text-xs"><span className="text-[#666672]">{name}</span><strong>{!hour || hour.closed ? "Kapalı" : `${shortTime(hour.opensAt)}–${shortTime(hour.closesAt)}`}</strong></div>; })}</div></div></div></section></div>
      <aside className="hidden lg:block"><div className="sticky top-24 surface soft-shadow p-5"><div className="flex items-center justify-between"><div><span className="text-xs text-[#777781]">Başlangıç</span><strong className="block text-xl">{business.startingPrice ? price(business.startingPrice) : "Fiyat seçime göre"}</strong></div>{business.open && <Badge tone="green">Şimdi açık</Badge>}</div><ButtonLink href={`/booking/${business.slug}`} className="mt-5 w-full">Uygun Saatleri Gör</ButtonLink><p className="mt-5 border-t border-[#ECECF1] pt-5 text-center text-[11px] leading-5 text-[#91919A]">Kesin fiyat, çalışan ve işletmenin iptal koşulları onay adımında gösterilir.</p></div></aside></section>
  </main><div className="fixed inset-x-0 bottom-[69px] z-40 border-t border-[#E8E8EE] bg-white px-4 py-3 md:hidden"><ButtonLink href={`/booking/${business.slug}`} className="h-12 w-full rounded-xl text-sm">Randevu Al</ButtonLink></div><MobileNav /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify([localBusiness, breadcrumb]).replace(/</g, "\\u003c") }} /></>;
}
function Empty({ text }: { text: string }) { return <div className="mt-5 rounded-2xl border border-dashed border-[#DDD9EF] bg-[#FAF9FF] p-6 text-sm text-[#777781]">{text}</div>; }
